### ISSUE TITLE
macOS Big Sur 11.1, Security Update 2020-001 Catalina, Security Update 2020-007 Mojave

### ISSUE THREAD

**Issue by alex** [fishinabarrel/analysis#199]
https://support.apple.com/en-us/HT212011

40/59

**Comment by reaperhulk** [comment]
I'd like to split out the Big Sur specific numbers for future "state of Apple's platforms" blog posts. I'll tweet this too, but we should dig out the Big Sur specific stuff.

**Comment by reaperhulk** [comment]
14/18 is my count for just Big Sur.

Open question on 27941 and 27946 (both counted as not memory safety in the above count)

**Comment by reaperhulk** [comment]
counting 27946 as memory unsafety so we'll do 41/59 (15/18 Big Sur)
