### ISSUE TITLE
You Really Shouldn't Roll Your Own Crypto: An Empirical Study of Vulnerabilities in Cryptographic Libraries

### ISSUE THREAD

**Issue by alex** [fishinabarrel/analysis#336]
https://arxiv.org/abs/2107.04940

> Among our most interesting findings is that only 27.2% of vulnerabilities in cryptographic libraries are cryptographic issues while 37.2% of vulnerabilities are memory safety issues

**Comment by reaperhulk** [comment]
I retweeted a tweet about this earlier in the morning
