### ISSUE TITLE
Tweet the CISA ITW analysis blog post

### ISSUE THREAD

**Issue by noncombatant** [fishinabarrel/analysis#475]
Alex says I should file this bug with a suggested pull quote. I propose: "The people building the infrastructure of our world, and bodies like the Cyber Safety Review Board, are most effective when they have all the facts at hand. We need Feynman explaining the Challenger explosion, not handwaving." (Maybe shorten it to CSRB if too many characters.)

**Comment by alex** [comment]
Link: https://noncombatant.org/2022/04/22/itw-taxonomy/
